"""API V1.0.0

Revision ID: 63b58d3bbb5e
Revises: 8b46272aa05d
Create Date: 2025-08-30 19:51:11.672676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b58d3bbb5e'
down_revision: Union[str, Sequence[str], None] = '8b46272aa05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sysname', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_types_id'), 'product_types', ['id'], unique=False)
    op.create_index(op.f('ix_product_types_name'), 'product_types', ['name'], unique=False)
    op.create_index(op.f('ix_product_types_sysname'), 'product_types', ['sysname'], unique=True)
    op.add_column('categories', sa.Column('product_type_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('ix_categories_sysname'), table_name='categories')
    op.create_foreign_key(None, 'categories', 'product_types', ['product_type_id'], ['id'], ondelete='SET NULL')
    op.drop_column('categories', 'sysname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('sysname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_index(op.f('ix_categories_sysname'), 'categories', ['sysname'], unique=True)
    op.drop_column('categories', 'product_type_id')
    op.drop_index(op.f('ix_product_types_sysname'), table_name='product_types')
    op.drop_index(op.f('ix_product_types_name'), table_name='product_types')
    op.drop_index(op.f('ix_product_types_id'), table_name='product_types')
    op.drop_table('product_types')
    # ### end Alembic commands ###
