"""test categories

Revision ID: f2124d3601e8
Revises: 00f2693469f4
Create Date: 2025-08-26 18:08:21.339288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2124d3601e8'
down_revision: Union[str, Sequence[str], None] = '00f2693469f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_leaf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_leaf', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
